name: 'canadian_house_prices'
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.12
    - pandas=2.2
    - altair=5.3
    - ipykernel
    - altair-all
    - dash
    - dash-bootstrap-components
    - plotly
    - tabulate  # df.to_markdown()
    - lxml  # pd.read_html()
    - pip=24.0
    - pip:
        - dash-vega-components